apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-msg
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-app
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cj-cont
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "Hello from Kubernetes cluster"
