apiVersion: v1
kind: Pod
metadata:
  name: external-pod
  labels:
    app: my-app3
  namespace: external-namespace
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
