apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: node-namespace
spec:
  type: NodePort
  selector:
    app: my-app2
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: 80
