apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: my-app2
  namespace: node-namespace
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
      - containerPort: 80
