apiVersion: batch/v1
kind: Job
metadata:
  name: retry-job
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: busybox
        command: ["sh", "-c", "mkdir -p /output && echo 'Hello from job' > /output/hello.txt && cat /output/hello.txt"]
      restartPolicy: OnFailure
  backoffLimit: 5
